"""Create user table

Revision ID: 308a74453989
Revises: 
Create Date: 2025-03-05 23:35:45.702038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308a74453989'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
